signals:
  app:
    use: true
    NN: 8
    coreset: 1
    denoise_scorename: "aerecon"
    percentile_denoise: 75

  mot:
    use: true
    NN: 8
    coreset: 1
    denoise_scorename: "velo_fgmm"
    percentile_denoise: 75

postprocess:
  sigma: 5
